### ISSUE TITLE
suggestion: initial tag suggestions

### ISSUE THREAD

**Issue by fallax** [AndreaUnlimited/starfriends#2]
Currently there is no support for encouraging people to put down tags that cover the "basics" that most dating sites would expect their users to enter: stuff like smoker/non-smoker, children/no children. We've got tags for this but you have to go searching through the tags and they aren't in much use. Getting people to answer some basic questions at sign-up - or suggesting some tags at the top of the edit tags page - might help with this.

**Comment by Cassolotl** [comment]
The [Edit Tags page](https://www.starfriends.org/edit/tags) now contains this handy text thing:

![screen shot 2017-02-11 at 18 32 42](https://cloud.githubusercontent.com/assets/6607512/22856399/92a8eda2-f088-11e6-9257-ace5f8b7c523.png)

It's not intended to replace this issue, but it does make it a little easier for new users to find commonly used tags to get them started.

I think Andréa is planning something a lot more like this suggestion though, so I'll mark it "To Do", and if I find out anything different I'll put something here to let you know.

**Comment by Cassolotl** [comment]
Update! We don't want to influence people too much with suggested tags, but the All Tags page has all the tags plus sections called Hot, Most Recent, Most Used, and Important. So that makes it pretty easy to find inspiration for tags if you're stuck, and that's the intended fix for this issue unless someone comes up with something better.
