### ISSUE TITLE
Prompt old users to update location settings

### ISSUE THREAD

**Issue by fallerOfFalls** [AndreaUnlimited/starfriends#89]
When an old user hasn't changed their location settings since the new location system was added, a (dismissals) notice could be displayed in settings to encourage them to make a choice (rather than just leave it as it is). Currently there are very few users who have updated their settings.

**Comment by Cassolotl** [comment]
Andréa is working on a walk-through for new users that will include being prompted to update settings such as location, so that's pretty cool. Everyone will have to do this when they log in after launch.

So doing this for just people who haven't updated since the location settings were added is no longer needed, we think.
